folder: ./module3
build:
  - target: default
run:
  # Config 1: 512 threads, block size 256
  - [512, 256]
  # Config 2: 1024 threads, block size 512
  - [1024, 512]
  # Config 3: 2048 threads, block size 256
  - [2048, 256]